var index = require('../index.js');
	this.data = [{
        label:"Debug logs",
        isSearchable:true,
        formainmenu:true,
        tooltipMessage:"View all logs on salesforce",
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"Debug logs are not available for you, click on new to record debug logs.",
        value:"DebugLogs",
        metadata:"ApexLog",
        type:"table",
        eligibleForPackageXml:false,
        menuname:"favourite",
        queryForAll:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog order by StartTime desc",
        queryForAllWithWhere:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog where Operation like ",
        query:"SELECT Id, LogUser.Name, LogUserId, LogLength, LastModifiedDate, Request, Operation, Application, Status, DurationMilliseconds, SystemModstamp, StartTime, Location FROM ApexLog where LogUserId= order by StartTime desc",
        headers:["Log Size(byte)", "Operation", "Start Time"],
        
        fieldlevelactions:[{}],
        listUrl:"/setup/ui/listApexTraces.apexp",
        midurl:"",
        placeholderText:"Search by size/operation/time/user..."
    },{
        label:"Classes",
        value:"Classes",
        isSearchable:true,
        formainmenu:true,
        tooltipMessage:"View all classes on salesforce",
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any class.",
        menuname:"favourite",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexClass order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexClass where name like ",
        query:"SELECT Id, Name, LastModifiedDate, LastModifiedBy.Id,  IsValid, ApiVersion, NamespacePrefix, CreatedBy.Name, LastModifiedBy.Name FROM ApexClass where  LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"ApexClass",
        type:"table",
        headers:["Edit", "Download", "Name"],
        listUrl:"/01p",
        midurl:"",
        placeholderText:"Quick find/search class..."
    },{
        label:"Triggers",
        value:"Triggers",
        tooltipMessage:"View all triggers on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any triggers.",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"ApexTrigger",
        type:"table",
        headers:["Edit", "Download", "Name"],
        listUrl:"/setup/build/allTriggers.apexp",
        midurl:"",
        placeholderText:"Quick find/search triggers..."
    },{
        label:"Aura Definition",
        value:"AuraDefinitionBundle",
        tooltipMessage:"Open Developer Console",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any lightening components.",
        menuname:"favourite",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where  LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"AuraDefinitionBundle",
        type:"table",
        headers:[],
        listUrl:"/_ui/common/apex/debug/ApexCSIPage",
        midurl:"",
        placeholderText:"Quick find/search class..."
    },{
        label:"Pages",
        value:"Pages",
        tooltipMessage:"View all pages on salesforce",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any visualforce pages.",
        menuname:"favourite",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexPage order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, NamespacePrefix, createdby.Name, LastModifiedBy.Name from ApexPage where name like ",
        query:"select id, Name, ApiVersion, createdby.name, NamespacePrefix, LastModifiedDate, LastModifiedBy.Name from ApexPage where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"ApexPage",
        type:"table",
        headers:["Edit", "Security", "Name"],
        listUrl:"/apexpages/setup/listApexPage.apexp",
        midurl:"",
        placeholderText:"Quick find/search pages..."
    },{
        label:"Components",
        value:"Components",
        tooltipMessage:"View all components on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any visualforce components.",
        queryForAll:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexComponent where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"ApexComponent",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/apexpages/setup/listApexComponent.apexp",
        midurl:"",
        placeholderText:"Quick find/search components..."
    },{
        label:"Objects",
        value:"Objects",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom objects.",
        queryForAll:"select id, DeveloperName, ExternalName, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomObject order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, ExternalName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomObject where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, ExternalName, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomObject where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"CustomObjects",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search objects..."
    },{
        label:"Fields",
        value:"Fields",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom fields.",
        queryForAll:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"CustomFields",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search fields..."
    },{
        label:"Labels",
        value:"Labels",
        tooltipMessage:"View all labels on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom labels.",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomLabel order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomLabel where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomLabel where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"CustomLabel",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/101",
        midurl:"",
        placeholderText:"Quick find/search labels..."
    },{
        label:"Workflows",
        value:"Workflows",
        tooltipMessage:"View all workflows on salesforce",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name from WorkflowRule order by LastModifiedDate desc",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any workflows.",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"WorkflowRule",
        headers:["Edit", "Name"],
        type:"table",
        listUrl:"/_ui/core/workflow/WorkflowSplashUi?EntityId=WorkflowRule",
        midurl:"",
        placeholderText:"Quick find/search workflow..."
    },{
        label:"Flows",
        value:"Flows",
        tooltipMessage:"View all flows on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any flows.",
        queryForAll:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"Flows",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/300",
        midurl:"",
        placeholderText:"Quick find/search flows..."
    },{
        label:"Email Templates",
        value:"EmailTemplates",
        tooltipMessage:"View all email templates on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any email templates.",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix,  LastModifiedBy.Name from EmailTemplate order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where LastModifiedById= or CreatedById= order by LastModifiedDate desc ",
        metadata:"EmailTemplates",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/00X",
        midurl:"",
        placeholderText:"Quick find/search email template..."
    },{
        label:"Users",
        value:"Users",
        tooltipMessage:"View all users on salesforce",
        isSearchable:true,
        forAdvanceSearchOnly:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any users.",
        queryForAll:"select id, name, email, username, LastModifiedBy.Name from User where user.IsActive = true order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, email, username, LastModifiedBy.Name from User where user.IsActive = true and name like ",
        query:"select id, name, email, username, LastModifiedBy.Name from User where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"Users",
        type:"table",
        listUrl:"/005",
        midurl:"",
        placeholderText:"Quick find/search Users..."
    },{
        label:"Static Resource",
        value:"StaticResource",
        tooltipMessage:"View all static resources on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any static resource.",
        queryForAll:"select id, name, LastModifiedBy.Name, NamespacePrefix from StaticResource order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where name like ",
        query:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"StaticResource",
        type:"table",
        headers:["Edit", "Name"],
        listUrl:"/081",
        midurl:"",
        placeholderText:"Quick find/search Resource..."
    },{
        label:"Profile",
        value:"Profile",
        tooltipMessage:"View all profiles on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any profile.",
        queryForAll:"SELECT Id, Name, LastModifiedBy.name FROM Profile order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, LastModifiedBy.name FROM Profile where name like ",
        query:"SELECT Id, Name, LastModifiedBy.name FROM Profile where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"Profile",
        type:"table",
        headers:["Edit", "Clone", "Name"],
        listUrl:"/00e",
        midurl:"",
        placeholderText:"Quick find/search Profile..."
    },{
        label:"Group",
        value:"Group",
        tooltipMessage:"View all groups on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any group.",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"Group",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"setup/own/groupdetail.jsp?id=",
        listUrl:"/p/own/OrgPublicGroupsPage/d",
        midurl:"setup/own/groupdetail.jsp?id=",
        placeholderText:"Quick find/search Group..."
    },/*{
        label:"Coverage",
        value:"ApexCodeCoverageAggregate",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"Coverage show you real time code coverage of your current your.",
        queryForAll:"SELECT Id,createdDate, ApexClassorTrigger.Name,ApexClassorTriggerId,NumLinesCovered,NumLinesUncovered,Coverage FROM ApexCodeCoverageAggregate Order By CreatedDate DESC",
        metadata:"ApexCodeCoverageAggregate",
        type:"table",
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        forAdvanceSearchOnly:true,
        placeholderText:"Quick find/search Coverage..."
    },{
        label:"Settings",
        value:"Settings",
        isSearchable:false,
        url:"",
        menuname:"favourite",
        objectlevelaction:[
                               {name:"User", actionUrl:""}, 
                               {name:"Favourite", actionUrl:""}
                           ]
    },*/{
        label:"RecordType",
        value:"RecordType",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Record Type.",
        queryForAll:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name FROM RecordType where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"setup/ui/recordtypefields.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Layout",
        value:"Layout",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Layout",
        queryForAll:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where DeveloperName like ",
        query:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[],
        midurl:"",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"AssignmentRule",
        value:"AssignmentRule",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        isSobjectType:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any Assignment rules.",
        queryForAll:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where DeveloperName like ",
        query:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"AssignmentRule",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"setup/own/entityruledetail.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"WebLink",
        value:"WebLink",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Weblink.",
        queryForAll:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink where DeveloperName like ",
        query:"SELECT Id, Name, LastModifiedBy.name, NamespacePrefix FROM WebLink where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        midurl:"",
        headers:["Edit", "Name"],
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"ListView",
        value:"ListView",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Listview.",
        queryForAll:"SELECT Id, DeveloperName, SobjectType, NamespacePrefix, LastModifiedBy.name FROM ListView order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, NamespacePrefix, LastModifiedBy.name FROM ListView where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name, NamespacePrefix FROM ListView where LastModifiedById= or CreatedById= order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    }];
	
	module.exports = function(metadata){
		this.getMetadata = function(){
			this.meta = metadata;
			this.metamap = new Map();
			for(var i=0; i<data.length; i++){
				this.metamap.set(data[i].value ,data[i]);
			}
			return this.metamap.get(this.meta);
		}
	}